### ISSUE TITLE
Error in build phase in compilation

### ISSUE THREAD

**Issue by ld3804** [tukl-msd/DRAMPower#83]
Hi,

I clone the repo with the pre-release tagged version **V5.0-RC-1,** and i have an error during the compilation with make (make -j4 DRAMPower).

My Cmake version is : **3.18.6**
The different version of gcc tested :  4.8.5, 4.9.3, 4.7.4.0 and 9.12.0

Here it is the error message after executing the command  : **$ make -j4 DRAMPower** :

```
[ 13%] Building CXX object src/DRAMPower/CMakeFiles/DRAMPower.dir/DRAMPower/memspec/MemSpecDDR5.cpp.o
[ 13%] Building CXX object src/DRAMPower/CMakeFiles/DRAMPower.dir/DRAMPower/command/CmdType.cpp.o
[ 13%] Building CXX object src/DRAMPower/CMakeFiles/DRAMPower.dir/DRAMPower/memspec/MemSpecDDR4.cpp.o
[ 13%] Building CXX object src/DRAMPower/CMakeFiles/DRAMPower.dir/DRAMPower/memspec/MemSpec.cpp.o
In file included from /home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/memspec/MemSpec.h:43:0,
                 from /home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/memspec/MemSpec.cpp:37:
/home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/command/CmdType.h: In function ‘constexpr const char* DRAMPower::to_string(DRAMPower::CmdType)’:
/home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/command/CmdType.h:93:1: error: body of constexpr function ‘constexpr const char* DRAMPower::to_string(DRAMPower::CmdType)’ not a return-statement
 };

In file included from /home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/memspec/MemSpec.h:43:0,
                 from /home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/memspec/MemSpecDDR4.h:41,
                 from /home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/memspec/MemSpecDDR4.cpp:38:
/home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/command/CmdType.h: In function ‘constexpr const char* DRAMPower::to_string(DRAMPower::CmdType)’:
/home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/command/CmdType.h:93:1: error: body of constexpr function ‘constexpr const char* DRAMPower::to_string(DRAMPower::CmdType)’ not a return-statement
 };
 ^
In file included from /home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/command/CmdType.cpp:1:0:
/home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/command/CmdType.h: In function ‘constexpr const char* DRAMPower::to_string(DRAMPower::CmdType)’:
/home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/command/CmdType.h:93:1: error: body of constexpr function ‘constexpr const char* DRAMPower::to_string(DRAMPower::CmdType)’ not a return-statement
 };
 ^
make[3]: *** [src/DRAMPower/CMakeFiles/DRAMPower.dir/DRAMPower/command/CmdType.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/memspec/MemSpec.h:43:0,
                 from /home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/memspec/MemSpecDDR5.h:4,
                 from /home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/memspec/MemSpecDDR5.cpp:1:
/home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/command/CmdType.h: In function ‘constexpr const char* DRAMPower::to_string(DRAMPower::CmdType)’:
/home/travaux/drampower/DRAMPower/src/DRAMPower/DRAMPower/command/CmdType.h:93:1: error: body of constexpr function ‘constexpr const char* DRAMPower::to_string(DRAMPower::CmdType)’ not a return-statement
 };
 ^
make[3]: *** [src/DRAMPower/CMakeFiles/DRAMPower.dir/DRAMPower/memspec/MemSpecDDR4.cpp.o] Error 1
make[3]: *** [src/DRAMPower/CMakeFiles/DRAMPower.dir/DRAMPower/memspec/MemSpecDDR5.cpp.o] Error 1
make[3]: *** [src/DRAMPower/CMakeFiles/DRAMPower.dir/DRAMPower/memspec/MemSpec.cpp.o] Error 1
make[2]: *** [src/DRAMPower/CMakeFiles/DRAMPower.dir/all] Error 2
make[1]: *** [src/DRAMPower/CMakeFiles/DRAMPower.dir/rule] Error 2
make: *** [DRAMPower] Error 2
```

Is it a known bug ? Have you an idea of the cause of the problem ?

Thanks

**Comment by IESE-T3** [comment]
Hello,

I just tried a fresh build with GCC 9.5 (A GCC version 9.12 doesn't seem to exist) and it worked without errors.
GCC 4.x would be most likely too old to compile without problems.

Could you please share more information about your system so we can help?

Best regards

**Comment by ld3804** [comment]
I work on a scientific linux 7 (based on red hat 7). What other in formations do you need ?

For the version of gcc, it was gcc-12.1.0 more particularly.  (yes, it does exists : 12.2 was released in August 2022)

I will try to test it on a Ubuntu in a virtual machine in the next days to see if it can solve the problem.

**Comment by ld3804** [comment]
I tried on a Ubuntu 20 with gcc 9.4.0 and it works ! 
 
On sl7 with gcc 9.2 the same error occur. 

Do I have to close the issue, or do you want to keep it open to solve the problem on sl7 ? If you need more information on my configuration, feel free to ask me.
